/**
 * @file upgrade_lesson_scripts.js
 * @description Programmatic data injection automation script. Replaces legacy brief lesson texts
 * across grade-specific curriculum files (`wordBank_2nd.json`, `wordBank_3rd.json`, `wordBank_5th.json`, `wordBank_6th.json`)
 * with immersive, fantasy-themed storytelling scripts (Minecraft, Star Wars, Harry Potter, LOTR, Narnia)
 * embedded with explicit vocabulary examples, similarity breakdowns, and phonic mnemonic rules.
 *
 * @example
 * // Execution syntax:
 * node upgrade_lesson_scripts.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const scriptsMap = {
  '2nd': {
    'tier_g2_t1': "Welcome, young Padawan! Your Jedi training begins with foundational CVC (Consonant-Vowel-Consonant) words. To master spelling, you must first understand the difference between vowels and consonants. Vowels (A, E, I, O, U) are open, flowing sounds made with an open mouth—they are the energy core of every word! Consonants are sounds where your lips, teeth, or tongue block the air, like building protective walls. In CVC words, two consonant walls 'close in' or trap the vowel in the middle, forcing it to make a quick, crisp 'short' sound. Just like stacking basic blocks in Minecraft to build a sturdy shelter before nightfall, you build these words one sound at a time. Master the short vowels, and the Force will be with you!",
    'g2_t1_s1': "In Minecraft, craft a 'MAP' to find a pink 'PIG', or watch Hermione's 'CAT' Crookshanks 'SIT' on a wizard's 'HAT'. Notice how the consonant letters trap the vowels in the middle! Short 'a' sounds like the crisp crunch of an apple (/a/), and short 'i' sounds like the start of an igloo (/i/). Keep your mouth open just a little for these short, quick vowel sounds to 'WIN' the spelling battle!",
    'g2_t1_s2': "As the twin 'SUN's of Tatooine set, you must 'RUN' from Creepers and hop into a red 'BED'! Today we explore short O, U, and E. Listen for the distinct middle sounds in Hagrid's loyal 'DOG', a magical wooden 'BOX' from Narnia, or Darth Vader's 'RED' lightsaber. Phonics tip: shape your mouth like a round 'O' for dog, drop your jaw for the /u/ in sun, and make a wide grin for the /e/ in red!",
    
    'tier_g2_t2': "Behold the power of the silent Magic E! Like a secret Jedi Master hiding in the shadows, the 'E' sits silently at the very end of a word. It uses the Force to jump backward over one single consonant and gives all its energy to the vowel before it, making that vowel shout its own long name! This magical rule transforms a short vowel word into a long vowel word. For example, adding Magic E turns the hat 'cap' into a hero's 'cape', and a bear 'cub' into a 3D 'cube'.",
    'g2_t2_s1': "Welcome to Hogwarts! Today we bake a giant birthday 'CAKE' for Harry and play a wizard chess 'GAME'. Notice how the silent 'E' at the end of 'TIME' and 'BIKE' magically forces the letter 'I' to shout its long name! Mnemonic: When 'E' is at the gate, the vowel says its name!",
    'g2_t2_s2': "Step into Bilbo's cozy Hobbit 'HOME' or climb down an elven 'ROPE'! Today we master long O and U. The magic E turns a Minecraft skeleton's 'BONE' into a long 'O' sound, and helps Mr. Tumnus play a beautiful 'TUNE' on his 'FLUTE' in Narnia. Remember: silent E stays quiet so the main vowel can shine!",
    
    'tier_g2_t3': "When two consonant heroes team up, they form powerful alliances! Consonant Blends keep both of their original sounds when they stand together, like the 'st' in 'star'—you can hear both the /s/ and the /t/. But Digraphs like 'sh', 'ch', and 'th' use magic to fuse together into a brand new single sound, just like crafting iron and wood together to make a shield!",
    'g2_t3_s1': "Enter Diagon Alley's wand 'SHOP' or sail across Narnia on a majestic 'SHIP'! Today we study Digraphs. 'SH' makes the quiet 'shh' sound, 'CH' makes the cheerful 'chat' sound, and 'TH' guides your 'PATH' through the Shire. Tip: place your tongue gently between your teeth when saying 'WITH' and 'THIS'!",
    'g2_t3_s2': "Look up at the massive Death 'STAR' or climb a Whomping Willow 'TREE'! Today we master consonant blends. When you take a 'STEP' into Narnia or 'FLIP' Anakin's starfighter to dodge a 'TRAP', you hear both consonant sounds blended smoothly together. Listen closely to each letter sound so you don't 'TRIP'!",
    
    'tier_g2_t4': "These legendary words appear everywhere across the galaxy! Some refuse to follow the normal rules of phonics, acting like rebellious space smugglers. We call these 'Sight Words'. You must take a mental snapshot and memorize them by heart, just as a wizard memorizes their most trusted spells!",
    'g2_t4_s1': "Welcome, Padawan! To read the ancient Jedi archives, you must instantly recognize sight words like 'THE', 'YOU', and 'THEY'. When Obi-Wan 'SAID' to use the Force, or when an owl arrives 'FROM' Hogwarts, these words keep the sentence flowing smoothly. Take a mental snapshot of each one!",
    'g2_t4_s2': "'WHAT' kind of magical creature is in Hagrid's pocket? 'WHEN' the sun rises in Minecraft, 'WHERE' do the skeletons go? Master tricky words like 'COME', 'SOME', and 'BEEN'. Mnemonic: 'COME' and 'SOME' look like 'home' but sound like 'hum'! Memorize them to unlock your spelling magic.",
    
    'tier_g2_t5': "Even in the farthest outer rim of the galaxy, math and science govern the universe! Whether calculating hyperspace jumps on the Millennium Falcon or brewing complex potions at Hogwarts, mastering academic vocabulary words gives you the tools to understand and describe the cosmos.",
    'g2_t5_s1': "Welcome to Potions class! When you 'ADD' ingredients or calculate the 'SUM' of Smaug's gold, you are using math! Whether measuring Harry's eleven-'INCH' wand or staring at a nine-'FOOT' Enderman, these terms help you measure the world. Remember: 'PLUS' brings things together!",
    'g2_t5_s2': "Step through the wardrobe and feel the cold Narnian 'WIND' and 'RAIN'! Science words describe the natural world, from the solid 'ROCK' of the Lonely Mountain to a Minecraft wheat 'SEED' planted in dark 'DIRT'. Watch your spelling 'GROW' as you explore the living universe!"
  },
  '3rd': {
    'tier_g3_t1': "Welcome, young apprentice! Today we master Vowel Teams. A vowel team is when two vowels stand side-by-side to create one powerful sound. When two vowels go walking, the first one usually does the talking, shouting its long name! Like Frodo and Sam joining forces on their quest, these vowels unite to overcome any spelling challenge.",
    'g3_t1_s1': "In Minecraft, wait for the 'RAIN' to stop before mining 'CLAY', or board the Hogwarts Express 'TRAIN'! Today we master AI and AY. Both teams make the long /a/ sound, but why do we use two different spellings? In the English language, words almost never end in the letter 'I'. Therefore, 'AI' is used in the middle of words like 'BRAIN' and 'PAINT', while 'AY' is used at the end of words like 'PLAY' and 'DAY'. Mnemonic: AI stays inside, AY plays at the end!",
    'g3_t1_s2': "Encounter a giant walking 'TREE' Ent in LOTR, admire Yoda's 'GREEN' skin, or join the Gryffindor Quidditch 'TEAM'! Both EE and EA make the long E sound. Dumbledore needs 'SLEEP', and Hermione loves to 'READ'. Mnemonic: double E cheers long E loud and proud, EA teams up to lead!",
    'g3_t1_s3': "Cross a deep river in a 'BOAT' or watch the Narnian wind 'BLOW' 'SNOW' onto your fur 'COAT'! Today we explore OA and OW. The 'OA' team floats in the middle of 'GOAT' and 'TOAD', while 'OW' makes crops 'GROW' and swords 'GLOW' at the end. Mnemonic: OA floats inside, OW blows at the end!",
    
    'tier_g3_t2': "Affixes are magical word parts added to a root or base word! A base word is a complete word that can stand alone, like 'help'. Prefixes attach to the front of a base word to change its destiny and meaning. Suffixes attach to the end of a base word to change its grammatical part of speech (like turning an action verb into an adjective). Master these building blocks to expand your spellbook without having to invent new words!",
    'g3_t2_s1': "Gollum was 'UNHAPPY' to lose his ring, Hermione used magic to 'UNLOCK' doors, and Sauron tried to 'REMAKE' the world! Prefixes attach to the front of base words. 'UN-' and 'DIS-' mean 'opposite' or 'not'. For example, adding 'un-' to 'happy' changes the meaning entirely: 'Gollum was happy' vs 'Gollum was unhappy'. The prefix 'RE-' means 'again', so when you 'REREAD' an ancient scroll, you read it a second time!",
    'g3_t2_s2': "Sam was a 'HELPFUL' companion to Frodo, and you must be 'CAREFUL' mining near lava in Minecraft so you don't suffer 'PAINFUL' burns! Suffixes attach to the end of base words. '-FUL' means 'full of'. Let's examine how this changes a word in a sentence: 'Sam wanted to **help** Frodo' ('help' is an action verb). 'Sam was a **helpful** friend' ('helpful' is an adjective describing Sam, meaning he is full of help). Suffixes let you adapt words to fit perfectly into your sentences!",
    
    'tier_g3_t3': "Break massive words into manageable blocks! Compound words weld two independent, complete base words together like building a Minecraft castle out of stone and wood. Multi-syllable words can be split between consonant cores like chopping firewood in the Shire.",
    'g3_t3_s1': "Enjoy warm 'SUNSHINE' in the Shire, pack your Minecraft 'BACKPACK', or catch a 'SNOWFLAKE' in Narnia! Compound words fuse two complete words into one. Look closely to spot 'BUTTER' and 'FLY' in 'BUTTERFLY', or 'CAMP' and 'FIRE' in 'CAMPFIRE'. Mnemonic: find the two smaller words hiding inside!",
    'g3_t3_s2': "Radagast traveled with giant 'RABBIT's, Gimli swung a heavy 'HAMMER', and Narnia suffered an endless 'WINTER'. When spelling multi-syllable words, slice directly between the double consonants (RAB-BIT, KIT-TEN, SUD-DEN, LES-SON). This splits the word into easy, bite-sized pieces!",
    
    'tier_g3_t4': "Beware the Jedi mind trick of Homophones! Homophones are words that sound identical when spoken, but have completely different spellings and meanings. You must evaluate sentence context clues to choose your correct spelling path.",
    'g3_t4_s1': "Frodo could 'SEE' (with his eyes) the dark tower, while elven ships sailed on the salt 'SEA' (the ocean). You need 'TWO' (number 2) galleons 'TO' (direction) 'BUY' (purchase) a wand 'TOO' (also)! Use context clues to know when to write 'FOR' (purpose) versus 'FOUR' (number). Context is your spelling compass!",
    
    'tier_g3_t5': "Math and Science govern the entire galaxy! Whether brewing potions at Hogwarts or calculating hyperspace routes on Star Wars starships, academic terms are your ultimate analytical tools.",
    'g3_t5_s1': "Welcome to Potions and Arithmancy! When you 'ADD' potion drops, 'SUBTRACT' rings of power from Sauron, or calculate the 'TOTAL' 'SUM' of Erebor's gold, you are mastering math vocabulary. These words help you 'MEASURE' and 'GRAPH' the exact 'SHAPE' and 'PATTERN' of the universe!",
    'g3_t5_s2': "Study Professor Sprout's Mandrake 'PLANT', admire Aslan the talking 'ANIMAL', or feel the Star Wars 'FORCE' and 'ENERGY' across 'SPACE'! Science vocabulary categorizes matter into 'SOLID' rock, bubbling 'LIQUID' potions, and dragon breath 'GAS'. Master them to explore any 'PLANET'!"
  },
  '4th': {
    'tier_g4_t1': "Welcome, young Padawan. Today we master Complex Vowel Patterns and R-controlled nuances. Vowels are the energy core of every syllable. You will master advanced vowel teams, the famous 'I before E' rule, and the strict 'Bossy R' commander that forces vowels to change their sound entirely. Mastering these nuances will allow you to read ancient Jedi texts with absolute clarity!",
    'g4_t1_s1': "Today we study the most famous Jedi orthographic rule: 'I before E, except after C'! Whenever you hear the long 'E' sound in a word, like in 'PIECE' or 'SHIELD', the letter 'I' comes first. However, if the letter 'C' stands directly before the vowel team, like a Sith Lord trying to trick you, the 'E' jumps in front! That is why we spell 'RECEIPT' and 'CEILING' with 'EI'. Memorize this rule to guard against spelling traps!",
    'g4_t1_s2': "The 'I before E' training continues! Watch the White Witch act as a 'FIERCE' warrior, or feel 'RELIEF' when a Creeper falls into a pit. Notice how words like 'GRIEF' and 'YIELD' keep the 'I' before 'E' because there is no 'C' in front of them. But beware of exceptions like 'REINDEER' and 'WEIGH', where the vowel team makes a long /a/ sound! Rule: I before E, except after C, or when sounding like 'A' as in neighbor and weigh!",
    'g4_t1_s3': "When double 'E's team up, they cheer their long 'E' sound together loud and proud! Think of a computer 'SCREEN' displaying Death Star plans, or a tiny cave spider trying to 'SQUEEZE' through a block in Minecraft. Whether Dumbledore gives a welcoming 'SPEECH' or you feel a cold Quidditch 'BREEZE', two E's standing together will always make the long /e/ sound.",
    'g4_t1_s4': "Beware, young learner! The 'EA' Vowel Team is a master of disguise. While it often makes a long /e/ sound (as in 'team'), today we are hunting its deceptive side: the short /e/ sound! In words like 'SWEAT', 'BREATH', and 'MEADOW', the 'EA' team tricks you by sounding exactly like a single short 'E'. When Smaug takes a fiery 'BREATH' or you walk through a Narnian 'MEADOW', remember that a sneaky 'A' is hiding inside!",
    'g4_t1_s5': "Listen closely! The 'OU' and 'OW' vowel teams are loud and bold. When they combine, they make the shouting /ow/ sound, like you just stubbed your toe on a piece of unbreakable bedrock! You will hear 'OU' inside words like 'CLOUD' and 'CROWD', while 'OW' appears at the ends of syllables like 'PROWL' and 'DROWN'. Never be a 'COWARD' when spelling these bold vowels!",
    'g4_t1_s6': "You have encountered the Bossy R! The letter 'R' acts like a strict Republic Commander. When it stands directly after a vowel, it takes over the syllable and changes the vowel's sound entirely. 'A' and 'R' combine to make the pirate sound /ar/, like a blaster hitting a 'TARGET' or freezing Han Solo in 'CARBON'. 'O' and 'R' combine to make /or/, like standing on the 'BORDER' of Narnia. Listen to the commander!",
    'g4_t1_s7': "Behold the power of the Magic E! When an 'E' sits silently at the end of a word, it uses the Force to jump backward over one single consonant and make the first vowel shout its own long name! It turns short vowels into long vowels, transforming 'escape' (long A) and 'pirate'. It also gives long /u/ sounds to the 'VOLUME' of your speaker or Dumbledore's Halloween 'COSTUME'!",
    
    'tier_g4_t2': "Construct words like a master builder crafting a lightsaber! In advanced morphology, words are built around ancient base roots from Latin and Greek. A root holds the core meaning of a word. By attaching prefixes to the front and suffixes to the end, you can unlock dozens of complex vocabulary words and understand their precise meanings in your reading.",
    'g4_t2_s1': "Today we construct words using the ancient Latin root 'STRUCT', which literally means 'to build'. Let's break down how prefixes combine with this root: attaching 'con-' (together) creates 'CONSTRUCT' (to build together). Attaching 'de-' (down/away) creates 'DESTRUCT' (to tear down). If Professor McGonagall needs to 'INSTRUCT' (build knowledge into) her students, she relies on this structural root!",
    'g4_t2_s2': "Focus your mind on the Latin root 'PORT', which means 'to carry'. This is why a space vessel is called a 'TRANSPORT'—it literally carries (port) across (trans) the galaxy! If you carry goods out of Mirkwood, you 'EXPORT' (ex- + port) them. If an item is easy to carry in your Minecraft inventory, it is 'PORTABLE' (port + -able). Carrying this root in your memory unlocks immense vocabulary!",
    'g4_t2_s3': "We combine two powerful Greek roots today: 'TELE' (meaning 'at a distance') and 'BIO' (meaning 'life'). If you want to see stars at a massive distance, you use a 'TELESCOPE' (tele- + scope). If you want to study the living systems of alien Formic bugs, you study 'BIOLOGY' (bio- + -logy). Knowing these ancient Greek codes allows you to instantly decode massive academic words!",
    'g4_t2_s4': "A prefix is a piece of armor attached to the front of a word to change its destiny. Today we use 'UN-' (meaning 'not') and 'RE-' (meaning 'again'). Let's look at a sentence transformation: 'Gollum was **happy** with his ring' vs 'Gollum was **unhappy** when Bilbo stole it'—adding 'un-' flips the meaning to its exact opposite! When Steve needs to 'REBUILD' his house, 're-' tells us he must build it again!",
    'g4_t2_s5': "More prefixes, Padawan! We are studying 'PRE-' (meaning 'before') and 'DIS-' (meaning 'opposite' or 'apart'). When Mrs. Weasley casts a spell to 'PREHEAT' the oven, she heats it *before* cooking. When Ender and Peter 'DISAGREE', they hold opposite opinions. Use these prefixes to twist and shape your base words into new concepts!",
    'g4_t2_s6': "A suffix attaches to the end of a word to change its grammatical purpose. The suffix '-ABLE' turns verbs into adjectives meaning 'capable of'. If an ancient map is 'READABLE', it is capable of being read. The suffix '-FUL' means 'full of'. Let's examine sentence roles: 'The ewoks shouted with **joy**' (noun). 'The ewoks threw a **joyful** celebration' (adjective describing celebration). Look to the suffix to know how a word behaves!",
    
    'tier_g4_t3': "Focus your mind, young Padawan! Long multi-syllabic words can seem intimidating, like a towering Sith Lord. But we use our Jedi lightsaber strike to slice them into smaller, manageable syllable chunks! Every syllable must have exactly one vowel sound. You will also learn to identify and defeat the elusive 'Schwa'—a lazy vowel sound in unstressed syllables.",
    'g4_t3_s1': "First, master the VC/CV rule (Vowel-Consonant/Consonant-Vowel). When two consonants stand between two vowels, like clone troopers standing shoulder-to-shoulder, you slice right between them! Think of the word 'RABBIT'. You slice between the double consonants: RAB-BIT! Do the exact same strike for 'TEN-NIS', 'MAG-NET', and 'SUD-DEN' to turn big words into easy pieces.",
    'g4_t3_s2': "Next, master the V/CV rule (Vowel/Consonant-Vowel), also known as the Tiger rule! When only one single consonant stands between two vowels, you usually strike your lightsaber *before* the consonant. Think of the word 'TIGER'. It is sliced as TI-GER. Because the first syllable ends in a vowel, it is left 'open' and shouts its long name! Slice words like 'PA-PER' and 'SI-LENT' the exact same way.",
    'g4_t3_s3': "Beware! Sometimes the single consonant rule tricks you. This is the VC/V rule, or the Camel rule. If slicing before the consonant makes the word sound wrong, you strike *after* the consonant. This traps the first vowel, forcing it to make a short sound! Think of 'CAMEL'. You slice it as CAM-EL. Apply this trapping strike to words like 'CAB-IN' and 'PLAN-ET'!",
    'g4_t3_s4': "You have encountered the dark side of vowels: the Schwa! The Schwa is a lazy vowel sound. When a syllable is not stressed in speech, the vowel gives up its true sound and makes a lazy 'uh' grunt (/ə/). Today, we hunt the letter 'A' acting as a Schwa. In the word 'ABOUT', the 'A' does not sound like /a/ or /ae/; it sounds like 'uh-bout'! Memorize these tricky A-words!",
    'g4_t3_s5': "The lazy Schwa returns! This time, it has infected the letters 'E' and 'I'. In the word 'PENCIL', the unstressed 'I' makes a lazy 'uh' sound: 'pen-suhl'. In 'LISTEN', the 'E' becomes a Schwa: 'lis-uhn'. When Dumbledore has 'SPOKEN', listen for the 'spoh-kuhn' sound. Do not let the Schwa trick you into spelling these words with a 'U'!",
    'g4_t3_s6': "The final battle with the Schwa! The letters 'O' and 'U' are now making the lazy 'uh' grunt. In Hobbit 'CUSTOM', the 'O' sounds like 'cus-tuhm'. In a magical 'CIRCUS', the 'U' sounds like 'cir-kuhs'. When Smaug the 'DRAGON' roars, listen for 'drah-guhn'. You must rely on your visual memory to know which vowel letter is hiding behind the Schwa grunt!",
    
    'tier_g4_t4': "Beware, Padawan! You have entered the tricky realm of Homophones. These are words that sound exactly the same when spoken, like identical clone troopers, but they are spelled differently and have completely different meanings. You must analyze the surrounding sentence context to choose the correct spelling!",
    'g4_t4_s1': "Welcome to the cloning facility! Today we study 'THEIR', 'THERE', and 'YOU'RE'. 'THEIR' shows possession ('Their starship'). 'THERE' shows location and has the word 'here' hiding inside it ('Look over there!'). 'YOU'RE' is a contraction for 'you are', with an apostrophe taking the place of the 'a' ('You're a wizard!'). Use sentence replacement checks to pick the right clone!",
    'g4_t4_s2': "More homophone clones approach! Never confuse 'WRITE' (to put words on paper with a quill) with 'RIGHT' (morally correct or direction). Or 'KNEW' (past tense of knowing a fact, starting with a silent K) with 'NEW' (a brand new wand). When searching for the Golden Snitch 'HERE' (location), do not misspell it as 'HEAR' (perceiving sound with your 'ear')!",
    'g4_t4_s3': "The homophone duel continues! Do not feed a ferocious skin-changing 'BEAR' (animal) with your 'BARE' (uncovered) hands! If you need to stop the Hogwarts Express, you pull the 'BRAKE' (stopping device), you do not 'BREAK' (shatter into pieces) the train! You use galleons to 'BUY' (purchase) candy, you do not stand 'BY' (preposition) the cart!",
    'g4_t4_s4': "Context clues are your spelling compass! A 'DEER' (double E) is a four-legged magical creature, but 'DEAR' (EA) is an affectionate greeting for a letter. You use blue lapis lazuli 'DYE' (with a Y) to color your Minecraft bed, but if your health bar drops to zero, your character will 'DIE' (IE). You use baking 'FLOUR' for Hagrid's cake, but a beautiful 'FLOWER' grows in the greenhouse!",
    'g4_t4_s5': "More deceptive pairs! You use a magical potion to 'HEAL' (cure) your wounds, not your 'HEEL' (the back of your foot). You send an owl to deliver your 'MAIL' (letters), not a 'MALE' (boy/man) wizard. You eat roasted 'MEAT' (flesh) at the Welcome Feast, but you 'MEET' (encounter) your friends in the Gryffindor common room!",
    'g4_t4_s6': "The final homophone test! You eat a juicy green 'PEAR' (fruit), but you wear a 'PAIR' (set of two) of socks. You fly across the galaxy in a starship 'PLANE' (geometric flat surface or aircraft), but a blank sheet of parchment is 'PLAIN' (simple/undecorated). You climb the moving Hogwarts 'STAIR' (steps), but it is dangerous to 'STARE' (look fixedly) at an Enderman!",
    
    'tier_g4_t5': "Welcome to the Jedi Archives, scholar! Here we study Academic vocabulary—the specialized terminology used in Science, Math, and History. While these words appear complex, they hold immense precision. Mastering them will help you comprehend advanced textbooks and write spectacular, authoritative essays across all school subjects!",
    'g4_t5_s1': "To understand the living universe, you must master Biology vocabulary. 'PHOTOSYNTHESIS' combines Greek roots (photo = light, synth = put together) to describe how plants turn sunlight into food! An 'ECOSYSTEM' is a massive, balanced community of interacting organisms, like the forest moon of Endor. Master these terms to decode the secrets of life!",
    'g4_t5_s2': "Now we study Earth Science. The 'ATMOSPHERE' (using the Greek 'ph' for the /f/ sound) is the vital shield of gas protecting a planet from the cold vacuum of space. 'GRAVITY' is the universal force pulling you back to the ground when you jump in Minecraft. 'TECTONIC' plates shift beneath our feet to build mountains or trigger earthquakes!",
    'g4_t5_s3': "Mathematics is the universal language of logic! An 'EQUATION' demands absolute balance between two mathematical expressions. A 'FRACTION' (from the Latin root 'fract' meaning broken) is a broken piece of a whole number, like eating one slice of Bilbo's cake. To 'MULTIPLY' is to rapidly increase quantities, like cloning an army of droids!",
    'g4_t5_s4': "Geometry is the architecture of reality! A 'POLYGON' (poly = many, gon = angle) is a closed shape with straight lines—the entire Minecraft universe is built from them! The 'PERIMETER' is the absolute outer boundary of your base where you build defenses. 'VOLUME' measures the 3D space enclosed inside a container. Calculate perfectly to build masterpieces!",
    'g4_t5_s5': "History is the memory of human civilization! A 'CIVILIZATION' is an advanced society of intelligent beings. The ancient Egyptian 'PHARAOH' commanded the construction of massive, triangle-based 'PYRAMID' tombs. To 'CONQUER' is to take control of a realm by military force, like the evil Galactic Empire. Learn from the past to protect the future!",
    'g4_t5_s6': "Our final academic study: Revolutions! A 'REVOLUTION' is a sudden, dramatic overthrow of an oppressive government. A 'CONSTITUTION' is a sacred body of laws establishing how a nation is governed. 'LIBERTY' and 'FREEDOM' are the ultimate goals of every rebel fighting against the dark side. Use these powerful nouns to write compelling historical arguments!"
  },
  '5th': {
    'tier_g5_t1': "Welcome, young Padawan! Today we face the deceptive OUGH trigraph and complex diphthongs. Navigating these vowel patterns is as tricky as flying through an asteroid field. Use the Force to master their distinct sounds and understand their historical spelling rules!",
    'g5_t1_s1': "The 'OUGH' trigraph is a master of disguise! In Old English, this combination represented a deep throat sound that evolved over centuries into different modern pronunciations. In 'ALTHOUGH', it makes a long /o/ sound. In 'THOUGHT' and 'BROUGHT', it makes the /aw/ sound. In 'ROUGH' and 'TOUGH', it mimics /uff/. Group these words by their sound family to conquer them!",
    'g5_t1_s2': "Watch Han Solo the 'ASTRONAUT' pilot his ship, join the Narnian 'AUDIENCE' to 'APPLAUD' Aslan, or build an 'AUTOMATIC' Minecraft farm! The 'AU' vowel team creates the crisp /aw/ sound. Notice how 'AU' is almost always used at the beginning or in the middle of a word (like 'CAUTION'), because English spelling rules avoid ending words with 'u'!",
    'g5_t1_s3': "Edmund felt 'AWKWARD' meeting the White Witch, but the Argonath statues were truly 'AWESOME'. The 'AW' team also creates the /aw/ sound. Unlike 'au', 'AW' loves to sit at the very end of words or syllables (like 'FLAWLESS' and 'LAWLESS'), or before the letters L, N, and K ('SPRAWL'). Keep this placement rule in mind!",
    
    'tier_g5_t2': "Construct words like ancient Dwarves carving the halls of Moria! Latin roots hold the core meaning of advanced vocabulary. By understanding the base root and analyzing how prefixes attach to it, you can literally translate unfamiliar words and dramatically expand your reading comprehension.",
    'g5_t2_s1': "Lord Vader arrived to 'INSPECT' the Death Star, while Middle-earth showed 'RESPECT' to Aragorn. The Latin root 'SPECT' literally means 'to look or watch'. Let's break down the etymology: 'in-' (into) + 'spect' = to look closely into something. 'Re-' (back/again) + 'spect' = to look back at someone with admiration. Keep things in 'PERSPECTIVE' (looking through) as you analyze this root!",
    'g5_t2_s2': "Steve must 'CONSTRUCT' redstone 'INFRASTRUCTURE', while the Death Star activates its self-'DESTRUCT' sequence! The Latin root 'STRUCT' means 'to build'. Let's analyze: 'con-' (together) + 'struct' = to build together. 'De-' (down) + 'struct' = to tear down or destroy. An 'INSTRUCTOR' is someone who builds knowledge into your mind!",
    'g5_t2_s3': "The Arkenstone's glow will 'ATTRACT' greedy eyes, the White Witch will 'DISTRACT' Edmund, and Anakin's lightsaber will 'RETRACT'. The Latin root 'TRACT' means 'to drag or pull'. 'At-' (toward) + 'tract' = to pull toward. 'Dis-' (apart/away) + 'tract' = to pull your attention away. Whether using a 'TRACTOR' beam or signing a 'CONTRACT' (pulled together), this root pulls your vocabulary together!",
    
    'tier_g5_t3': "Defeating massive polysyllabic words is like battling an Ender Dragon! Slice them into prefixes, roots, and suffixes to conquer them easily. Suffixes are particularly powerful because they allow you to shift a word's part of speech, adapting a single concept to fit different grammatical roles in your writing.",
    'g5_t3_s1': "Creeper behavior is completely 'UNPREDICTABLE', Frodo 'DISAPPEARED' using the Ring, and Narnia is filled with 'SUPERNATURAL' magic! Prefixes attach to the front of a word. 'UN-', 'DIS-', and 'MIS-' ('MISUNDERSTANDING') flip the base word to its negative opposite. 'INTER-' means 'between', connecting nations in 'INTERNATIONAL'.",
    'g5_t3_s2': "R2-D2 enables galactic 'COMMUNICATION', Frodo bore the heavy 'RESPONSIBILITY', and entering Erebor was a major 'ACCOMPLISHMENT'. Suffixes attach to the end of a word. '-TION', '-ITY', and '-MENT' transform active verbs (like 'accomplish') or adjectives (like 'responsible') into formidable, conceptual nouns! Let's look at a sentence: 'Anakin wanted to **excite** the crowd' (verb) vs 'The crowd felt great **excitement**' (noun).",
    'g5_t3_s3': "Gandalf focused on the 'IDENTIFICATION' of the Ring, while the Pevensie 'DISAPPEARANCE' shocked their uncle. When facing mega-words with combined affixes ('UNPREDICTABILITY'), peel them off like onion layers! 'Un-' (not) + 'predict' (say before) + '-able' (capable of) + '-ity' (state of being) = the state of not being capable of being predicted!",
    
    'tier_g5_t4': "Welcome, master detective! Some words are shape-shifters, as deceptive as Sith Lords. Homophones sound alike but differ in spelling, while Homographs share exact spelling but shift their pronunciation and meaning depending on how they are used in a sentence.",
    'g5_t4_s1': "Aslan's return will 'AFFECT' (action verb meaning to influence) the winter, breaking its freezing 'EFFECT' (noun meaning the end result). Obi-Wan lived by the 'PRINCIPLE' (noun: a fundamental rule or belief) of protecting the 'PRINCIPAL' (adjective: main or most important) galaxy. Match your spelling to the grammatical role!",
    'g5_t4_s2': "Homographs share exact spelling but split meaning and sound! The Pevensies were 'CONTENT' (/kənˈtent/ - adjective meaning happy) with the 'CONTENT' (/ˈkänˌtent/ - noun meaning items inside) of Narnia. Steve had one 'MINUTE' (/ˈminət/ - unit of time) to examine the 'MINUTE' (/mīˈn(y)o͞ot/ - tiny) details of his 'PROJECT' (noun).",
    
    'tier_g5_t5': "Welcome, scholar! To excel at Hogwarts or the Jedi Academy, you must master academic terms. These subject-specific vocabulary words are your keys to advanced knowledge across Science, Social Studies, Math, and Language Arts.",
    'g5_t5_s1': "Science vocabulary unlocks the physical world! Explore the forest 'ECOSYSTEM' of Endor, understand 'PHOTOSYNTHESIS' in Narnia's talking trees, or test Hermione's 'HYPOTHESIS' (an educated prediction) in Snape's 'LABORATORY'. Master concepts like 'GRAVITY', 'EVAPORATION', and 'RESPIRATION' to understand living 'ORGANISM's.",
    'g5_t5_s2': "Social Studies examines history and culture! Restoring the 'GOVERNMENT' and 'CONSTITUTION' of Narnia, fighting for 'DEMOCRACY' in the Galactic Senate, or studying the farming 'ECONOMY' and 'AGRICULTURE' of the Shire. Understand how a 'REVOLUTION' shapes human 'CIVILIZATION'!",
    'g5_t5_s3': "Math and ELA vocabulary pairs geometric precision with literary analysis! Steve's crafting table is a 'QUADRILATERAL' (quad = 4, lateral = sides) with 'PERPENDICULAR' sides and a secure 'PERIMETER'. In ELA, Frodo is our hero 'PROTAGONIST' (main character) fighting the evil 'ANTAGONIST' (opposing character) Sauron using 'METAPHOR' and 'ALLITERATION'."
  },
  '6th': {
    'tier_g6_t1': "Delve into the ancient roots of language! Advanced Greek roots form the backbone of scientific and academic vocabulary. By learning roots like bio- (life), geo- (earth), and photo- (light), you gain the power to decode sophisticated academic texts and understand complex scientific concepts instantly.",
    'g6_t1_s1': "Master 'BIO-', the Greek root for 'life'! Hermione excelled in magical 'BIOLOGY' (study of life), Endor boasts a lush 'BIOSPHERE' (sphere of life), and Minecraft jungles possess incredible 'BIODIVERSITY' (diversity of living things). Whether reading Dumbledore's 'BIOGRAPHY' (writing about a life) or admiring 'BIOLUMINESCENT' glow squids, BIO signals living systems!",
    'g6_t1_s2': "Explore 'GEO-', the Greek root for 'earth'! The dwarves of Erebor mastered 'GEOLOGY' (study of the earth's structure) to find the Arkenstone, while Gandalf mapped the vast 'GEOGRAPHY' (writing/mapping the earth) of Middle-earth. In Minecraft, mine deep to find an amethyst 'GEODE' or utilize 'GEOTHERMAL' (earth heat) energy. GEO grounds your spelling in physical earth!",
    'g6_t1_s3': "Capture 'PHOTO-', the Greek root for 'light'! Colin Creevey snapped a 'PHOTOGRAPH' (light drawing) of Harry, Minecraft crops rely on 'PHOTOSYNTHESIS' (putting together with light), and the Death Star superlaser unleashed a massive 'PHOTON' (particle of light) beam. Endermen are 'PHOTOSENSITIVE' (sensitive to light) and teleport away from bright flashes.",
    
    'tier_g6_t2': "Master the art of shape-shifting prefixes! Assimilated prefixes are clever word parts that change their final consonant letter to match the starting letter of the root word they attach to. This linguistic evolution happened over centuries to make pronouncing the combined word seamless and natural.",
    'g6_t2_s1': "It seemed 'IMPOSSIBLE' to destroy the Death Star, the Elves are 'IMMORTAL', and the dark side created an 'IMBALANCE' in the Force! The prefix 'IN-' (meaning 'not') assimilates into 'IM-' before roots starting with P, M, or B. Try saying 'in-possible' fast—your lips naturally close to make an /m/ sound! That is why we spell it 'IMPOSSIBLE'.",
    'g6_t2_s2': "The stone pillars of Narnia 'SUPPORT' a massive roof, while the realm had to 'SUFFER' a century of winter as the Empire tried to 'SUPPRESS' the Jedi. The prefix 'SUB-' (meaning 'under') assimilates into 'SUF-' or 'SUP-' depending on the root ('SUPPLANT', 'SUPPLEMENT'). Notice how smoothly your tongue glides from prefix to root!",
    'g6_t2_s3': "In Minecraft, 'COMBINE' damaged tools to repair them, cause a 'COMMOTION' in Gryffindor Tower, or show 'COMPASSION' like Luke Skywalker! The prefix 'CON-' (meaning 'together') assimilates into 'COM-' before roots starting with B, M, and P ('COMPETE', 'COMPILE'). We are stronger together when words flow perfectly!",
    
    'tier_g6_t3': "Listen to the underlying rhythm of language! Discover the elusive Schwa sound in unstressed syllables, and observe how shifting vocal stress across syllables transforms word meaning and grammatical function.",
    'g6_t3_s1': "Finding a pink sheep is a rare 'PHENOMENON', the sun sets on the Narnian 'HORIZON', and the author of dark spellbooks remains 'ANONYMOUS'. The elusive Schwa is a lazy, unstressed vowel sound whispering a soft /uh/ or /ih/ (like the 'a' in 'anonymous' or 'e' in 'SOVEREIGN'). Because unstressed vowels lose their crisp sound, you must rely on visual memory to master them!",
    'g6_t3_s2': "Notice how vocal stress shifts when words change grammatical form! The vocal beat shifts from 'PHO-to' (noun) to 'pho-TOG-ra-phy' (noun indicating the art), or from 'com-PETE' (verb) to 'com-PET-i-tive' (adjective). Whether admiring 'MAGNIFICENT' Minas Tirith or reading the 'DECLARATION' of the Empire, feel the rhythmic beat shift!",
    
    'tier_g6_t4': "Words are like a painter's palette! Discover shades of intensity to choose the exact right word for your writing, and become a word detective by using surrounding sentence context clues to decode unfamiliar high school vocabulary.",
    'g6_t4_s1': "Not all big things are merely 'big'. Minecraft map details are 'MINUTE' (tiny), Erebor held 'SUBSTANTIAL' gold, the Balrog was 'COLOSSAL', and the Death Star was 'FORMIDABLE'! Hermione was 'PETRIFIED' (frozen with fear) by the Basilisk, while Harry was 'ASTOUNDED' (shocked). Master exact shades of meaning to make your writing spectacular!",
    'g6_t4_s2': "When encountering mystery words, analyze surrounding context clues! Steve stood on a 'PRECARIOUS' (dangerously unstable) cliff, droids are 'UBIQUITOUS' (appearing everywhere) across the galaxy, and the beauty of Lothlórien felt 'EPHEMERAL' (fleeting/short-lived). Let the sentence context unlock the meaning!",
    
    'tier_g6_t5': "Prepare for the rigorous trials of high school! Master the heavy-hitting academic vocabulary used by advanced scholars to analyze complex arguments, evaluate scientific theories, and describe intricate societal structures.",
    'g6_t5_s1': "Master the scholar's analytical toolkit! Elrond must 'ANALYZE' (examine in detail) ancient texts, Hermione will 'SYNTHESIZE' (combine ideas) library books, and the Rebel Alliance will 'FORMULATE' (create systematically) battle plans. Use powerful analytical verbs like 'EVALUATE', 'ELABORATE', 'INFER', 'DEDUCE', and 'VALIDATE' to craft flawless essays!",
    'g6_t5_s2': "Build an unshakeable framework for your arguments! A redstone repeater is a vital 'COMPONENT' (part), the Death Star's 'FUNCTION' was intimidation, and Creeper explosions destroy wooden 'FRAMEWORK's. Use structural academic terms like 'FACILITATE' (make easy), 'IMPLEMENT' (put into action), 'MODIFY' (change), and 'INNOVATION' (new creation) to prove your perspective!"
  }
};

const grades = ['2nd', '3rd', '4th', '5th', '6th'];

grades.forEach(grade => {
  const filePath = path.join(__dirname, 'src', 'data', `wordBank_${grade}.json`);
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️ Skipping missing file: ${filePath}`);
    return;
  }

  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const gradeScripts = scriptsMap[grade] || {};

  data.tiers.forEach(tier => {
    const tierKey = `tier_${tier.id}`;
    if (gradeScripts[tierKey]) {
      tier.lessonScript = gradeScripts[tierKey];
    }

    tier.sections.forEach(section => {
      if (gradeScripts[section.id]) {
        section.lessonScript = gradeScripts[section.id];
      }
    });
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`✅ Successfully upgraded lesson scripts in ${filePath}`);
});

console.log('🎉 All lesson scripts upgraded successfully!');
